# Generated by Django 2.1.2 on 2018-10-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perritos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nuevo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_new', models.CharField(max_length=50)),
                ('Raza', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('Foto', models.ImageField(upload_to='media/')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
