# Generated by Django 2.1.2 on 2018-10-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perritos', '0002_nuevo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nuevo',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='nuevo',
            old_name='Foto',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='nuevo',
            old_name='Nom_new',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='nuevo',
            old_name='Raza',
            new_name='raza',
        ),
    ]
